version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
       - "80:80"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/logs/frontend:/var/log/nginx
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "80:80"
    env_file:                        
      - .env
    volumes:
      - ${WEBAPP_STORAGE_HOME}/logs/backend:/var/log/app
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:                    # Las variables de entorno para PostgreSQL
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${WEBAPP_STORAGE_HOME}/pgdata:/var/lib/postgresql/data
      - ${WEBAPP_STORAGE_HOME}/sql:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
