services:
  - type: web
    name: levis-file-uploader
    env: docker
    plan: free
    repo: https://github.com/giova-schade/levis-file-uploader
    branch: main
    buildCommand: docker-compose build
    startCommand: docker-compose up
    envVars:
      - key: WEBAPP_STORAGE_HOME
        value: /mnt/data
      - key: POSTGRES_USER
        value: tu_usuario_postgres
      - key: POSTGRES_PASSWORD
        value: tu_contraseña_postgres
      - key: POSTGRES_DB
        value: tu_bd_postgres
